DROP DATABASE IF EXISTS boarding;
CREATE DATABASE boarding;
USE boarding;
SET FOREIGN_KEY_CHECKS=0;
SET NAMES utf8;
SET character_set_client=utf8mb4;

CREATE TABLE condos (
  condoID INT(11) NOT NULL,
  columnID INT(11) NOT NULL,
  rowID INT(11) NOT NULL,
  groupID INT(11) NOT NULL,
  status ENUM('Enabled', 'Disabled') NOT NULL DEFAULT 'Enabled',
  description VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (condoID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO condos (condoID, columnID, rowID, groupID, status, description) VALUES
(1, 1, 1, 1, 'Enabled', NULL),
(2, 2, 1, 1, 'Enabled', NULL),
(3, 2, 1, 2, 'Enabled', NULL),
(4, 2, 2, 2, 'Enabled', NULL),
(5, 2, 3, 2, 'Enabled', NULL),
(6, 2, 4, 2, 'Enabled', NULL),
(7, 2, 5, 2, 'Enabled', NULL),
(8, 2, 2, 3, 'Enabled', NULL),
(9, 1, 2, 3, 'Enabled', NULL),
(10, 1, 2, 1, 'Enabled', NULL),
(11, 2, 2, 1, 'Enabled', NULL),
(12, 1, 1, 2, 'Enabled', NULL),
(13, 1, 2, 2, 'Enabled', NULL),
(14, 1, 3, 2, 'Enabled', NULL),
(15, 1, 4, 2, 'Enabled', NULL),
(16, 1, 5, 2, 'Enabled', NULL),
(17, 2, 1, 3, 'Enabled', NULL),
(18, 1, 1, 3, 'Enabled', NULL);

CREATE TABLE cats_food (
  catFoodID INT(11) NOT NULL AUTO_INCREMENT,
  catReservationID INT(11) NOT NULL,
  foodType ENUM('Own', 'Ours') NOT NULL,
  feedingInstructions TEXT NOT NULL,
  specialNotes TEXT DEFAULT NULL,
  foodAllergies ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  separateToFeed ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  noSlipBowl ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  plasticBowl ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  slowFeeder ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  elevatedFeeder ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  status ENUM('Active', 'Future') NOT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (catFoodID),
  FOREIGN KEY (catReservationID) REFERENCES cats_reservations(catReservationID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cats_medications (
  catMedID INT(11) NOT NULL AUTO_INCREMENT,
  catReservationID INT(11) NOT NULL,
  medName VARCHAR(255) NOT NULL,
  strength VARCHAR(100) DEFAULT NULL,
  dosage TEXT NOT NULL,
  frequency ENUM('AM', 'PM', '2X', '3X', 'As Needed', 'Other') NOT NULL,
  notes TEXT DEFAULT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (catMedID),
  FOREIGN KEY (catReservationID) REFERENCES cats_reservations(catReservationID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cats_reservations (
  catReservationID INT(11) NOT NULL AUTO_INCREMENT,
  condoID INT(11) NOT NULL,
  catName VARCHAR(255) NOT NULL,
  checkIn DATE NOT NULL,
  checkOut DATE NOT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (catReservationID),
  FOREIGN KEY (condoID) REFERENCES condos(condoID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE rooms (
  roomID INT(11) NOT NULL,
  columnID INT(11) NOT NULL,
  rowID INT(11) NOT NULL,
  groupID INT(11) NOT NULL,
  status ENUM('Enabled', 'Disabled') NOT NULL DEFAULT 'Enabled',
  description VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (roomID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO rooms (roomID, columnID, rowID, groupID, status, description) VALUES
(1, 1, 16, 2, 'Enabled', NULL),
(2, 1, 15, 2, 'Enabled', NULL),
(3, 1, 14, 2, 'Disabled', 'Maxx\'s Room'),
(4, 1, 13, 2, 'Enabled', NULL),
(5, 1, 12, 2, 'Disabled', 'Harley\'s Room'),
(6, 1, 11, 2, 'Enabled', NULL),
(7, 1, 10, 2, 'Enabled', NULL),
(8, 1, 9, 2, 'Disabled', 'Diesel\'s Room'),
(9, 1, 8, 1, 'Enabled', NULL),
(10, 1, 7, 1, 'Disabled', 'Banks\' Room'),
(11, 1, 6, 1, 'Enabled', NULL),
(12, 1, 5, 1, 'Enabled', NULL),
(13, 1, 4, 1, 'Enabled', NULL),
(14, 1, 3, 1, 'Disabled', 'Nakita\'s Room'),
(15, 1, 2, 1, 'Disabled', 'Ruby\'s Room'),
(16, 1, 1, 1, 'Disabled', 'Do Not Use'),
(17, 2, 16, 2, 'Enabled', NULL),
(18, 2, 15, 2, 'Enabled', NULL),
(19, 2, 14, 2, 'Enabled', NULL),
(20, 2, 13, 2, 'Disabled', 'Charlie Paschal\'s Room'),
(21, 2, 12, 2, 'Enabled', NULL),
(22, 2, 11, 2, 'Enabled', NULL),
(23, 2, 10, 2, 'Disabled', 'Kylo\'s Room'),
(24, 2, 9, 2, 'Enabled', NULL),
(25, 2, 8, 1, 'Enabled', NULL),
(26, 2, 7, 1, 'Enabled', NULL),
(27, 2, 6, 1, 'Disabled', 'Maxine\'s Room'),
(28, 2, 5, 1, 'Enabled', NULL),
(29, 2, 4, 1, 'Enabled', NULL),
(30, 2, 3, 1, 'Enabled', NULL),
(31, 2, 2, 1, 'Enabled', NULL),
(32, 2, 1, 1, 'Enabled', NULL),
(33, 3, 1, 1, 'Disabled', 'Dolly\'s Room'),
(34, 3, 2, 1, 'Disabled', 'Oggie\'s Room'),
(35, 3, 3, 1, 'Enabled', NULL),
(36, 3, 4, 1, 'Disabled', 'Lily\'s Room'),
(37, 3, 5, 1, 'Enabled', NULL),
(38, 3, 6, 1, 'Disabled', 'Queenie\'s Room'),
(39, 3, 7, 1, 'Enabled', NULL),
(40, 3, 8, 1, 'Disabled', 'Boomer Nixon\'s Room'),
(41, 3, 9, 2, 'Disabled', 'Maui\'s Room'),
(42, 3, 10, 2, 'Enabled', NULL),
(43, 3, 11, 2, 'Enabled', NULL),
(44, 3, 12, 2, 'Enabled', NULL),
(45, 3, 13, 2, 'Enabled', NULL),
(46, 3, 14, 2, 'Enabled', NULL),
(47, 3, 15, 2, 'Enabled', NULL),
(48, 3, 16, 2, 'Disabled', 'Remi Boxer\'s Room'),
(49, 4, 18, 2, 'Enabled', NULL),
(50, 4, 17, 2, 'Enabled', NULL),
(51, 4, 16, 2, 'Enabled', NULL),
(52, 4, 15, 2, 'Enabled', NULL),
(53, 4, 14, 2, 'Enabled', NULL),
(54, 4, 13, 2, 'Enabled', NULL),
(55, 4, 12, 2, 'Enabled', NULL),
(56, 4, 11, 2, 'Enabled', NULL),
(57, 4, 10, 2, 'Enabled', NULL),
(58, 4, 9, 1, 'Enabled', NULL),
(59, 4, 8, 1, 'Enabled', NULL),
(60, 4, 7, 1, 'Enabled', NULL),
(61, 4, 6, 1, 'Enabled', NULL),
(62, 4, 5, 1, 'Disabled', 'Mosey\'s Room'),
(63, 4, 4, 1, 'Enabled', NULL),
(64, 4, 3, 1, 'Enabled', NULL),
(65, 4, 2, 1, 'Enabled', NULL),
(66, 4, 1, 1, 'Disabled', 'Sully\'s Room');

CREATE TABLE dogs_food (
  dogFoodID INT(11) NOT NULL AUTO_INCREMENT,
  dogReservationID INT(11) NOT NULL,
  foodType ENUM('Own', 'Ours') NOT NULL,
  feedingInstructions TEXT NOT NULL,
  specialNotes TEXT DEFAULT NULL,
  foodAllergies ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  separateToFeed ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  noSlipBowl ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  plasticBowl ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  slowFeeder ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  elevatedFeeder ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  status ENUM('Active', 'Future') NOT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (dogFoodID),
  FOREIGN KEY (dogReservationID) REFERENCES dogs_reservations(dogReservationID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dogs_medications (
  dogMedID INT(11) NOT NULL AUTO_INCREMENT,
  dogReservationID INT(11) NOT NULL,
  medName VARCHAR(255) NOT NULL,
  strength VARCHAR(100) DEFAULT NULL,
  dosage TEXT NOT NULL,
  frequency ENUM('AM', 'PM', '2X', '3X', 'As Needed', 'Other') NOT NULL,
  notes TEXT DEFAULT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (dogMedID),
  FOREIGN KEY (dogReservationID) REFERENCES dogs_reservations(dogReservationID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dogs_reservations (
  dogReservationID INT(11) NOT NULL AUTO_INCREMENT,
  roomID INT(11) NOT NULL,
  dogName VARCHAR(255) NOT NULL,
  checkIn DATE NOT NULL,
  checkOut DATE NOT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (dogReservationID),
  FOREIGN KEY (roomID) REFERENCES rooms(roomID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE medications (
  medID INT(11) NOT NULL AUTO_INCREMENT,
  medName VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (medID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO medications (medID, medName) VALUES
(1, 'Actigall'),
(2, 'Allergenic Extract'),
(3, 'Alprazolam'),
(4, 'Amantadine'),
(5, 'Amoxicillin'),
(6, 'Anafranil'),
(7, 'Animax Ointment'),
(8, 'Antacid'),
(9, 'Anti-Itch Spray'),
(10, 'Antimicrobial Dog Wipes'),
(11, 'Apoquel'),
(12, 'Atopica'),
(13, 'Baytril'),
(14, 'Benadryl'),
(15, 'Benazepril'),
(16, 'Bethkis'),
(17, 'Calming Chews'),
(18, 'Calming Treats'),
(19, 'Carprofen'),
(20, 'Carprovet'),
(21, 'CBD Hemp'),
(22, 'Cefpodoxime'),
(23, 'Cephalexin'),
(24, 'Ceraven/CeraSoothe CHX+KET Wipes'),
(25, 'Cerenia'),
(26, 'Cetirizine'),
(27, 'Chlorhexidine Mousse'),
(28, 'Chlorhexidine Wipes'),
(29, 'Clavacillin'),
(220, 'Clavamox'),
(222, 'Clavulanate Potassium'),
(223, 'Clavulanic Acid'),
(30, 'Clomipramine'),
(31, 'Clopidogrel'),
(32, 'Comfort Pac-Meloxicam'),
(33, 'Composure'),
(34, 'ConZip'),
(218, 'Cortizone-10'),
(35, 'Cosequin'),
(36, 'Cyclosporine'),
(37, 'Dasuquin'),
(38, 'Daxbia'),
(39, 'Deltasone'),
(40, 'Denamarin'),
(41, 'Diethylstilbestrol'),
(42, 'Diflucan'),
(43, 'Digestion Vitamin'),
(44, 'Diphenhydramine'),
(45, 'Doggie Dailies Advanced Calming Chews'),
(46, 'Doggie Dailies Advanced Probiotics'),
(47, 'Doggie Dailies Hip & Joint Supplement'),
(48, 'Doggie Dailies Multivitamin'),
(49, 'Doxy-100'),
(50, 'Doxycycline'),
(51, 'Ear Cleaner'),
(52, 'Ear Flush'),
(53, 'Elixophylline'),
(224, 'ElleVet Hemp CBD'),
(54, 'Enalapril'),
(55, 'Endosorb'),
(56, 'Enrofloxacin'),
(57, 'Enulose'),
(58, 'Extina'),
(59, 'Eye Lube'),
(60, 'Eye Wash'),
(61, 'Famotidine'),
(62, 'Fenbendazole'),
(63, 'Fish Oil'),
(64, 'Flovent'),
(65, 'Fluconazole'),
(66, 'Fluoxetine'),
(67, 'Fluticasone'),
(68, 'FortiFlora'),
(69, 'Furosemide'),
(70, 'Gabapentin'),
(71, 'Galliprant'),
(72, 'Generlac'),
(73, 'Gengraf'),
(74, 'GenOne Topical Spray'),
(75, 'Glandex'),
(76, 'GlycoFlex'),
(77, 'Gralise'),
(78, 'Grapiprant'),
(79, 'Heartgard'),
(80, 'Honest Paws Well Pre+ Probiotic'),
(81, 'Horizant'),
(82, 'Hycodan'),
(83, 'Hydrocodone'),
(84, 'Imodium'),
(85, 'Incurin'),
(86, 'Interceptor Plus'),
(87, 'Joint Supplement'),
(88, 'Keflex'),
(89, 'Keppra'),
(90, 'Keppra XR'),
(91, 'Ketoconazole'),
(92, 'Kristalose'),
(93, 'Lactulose'),
(94, 'Lasix'),
(95, 'Latanoprost'),
(96, 'Levetiracetam'),
(97, 'Levo-T'),
(98, 'Levothyroxine'),
(99, 'Levoxyl'),
(100, 'Loperamide'),
(101, 'Lorcet-HD'),
(102, 'Lortab'),
(103, 'Lotensin'),
(104, 'Malmetazone Otic Suspension'),
(105, 'Maxitrol'),
(106, 'Melatonin'),
(107, 'Meloxicam'),
(108, 'Metamucil'),
(109, 'MetroCream'),
(110, 'Metrogel'),
(111, 'Metronidazole'),
(112, 'Mobic'),
(113, 'Mometamax Otic Suspension'),
(114, 'Monodox'),
(115, 'Movoflex'),
(116, 'Mozotic Otic Suspension'),
(117, 'Multi-Vitamin'),
(118, 'Multi-Vitamin Powder'),
(119, 'MYOS Canine Muscle & Joint Formula'),
(120, 'MYOS Canine Muscle Formula'),
(121, 'Neo-Poly-Dex'),
(122, 'Neo-Predef with Tetracaine Topical Powder'),
(123, 'Neoral'),
(219, 'Neosporin'),
(124, 'Neuraptine'),
(125, 'NexGard'),
(126, 'Nizoral'),
(127, 'Novox'),
(128, 'NuJoint DS Canine Wafers'),
(129, 'NuJoint Plus Canine Powder'),
(130, 'NuJoint Plus Canine Wafers'),
(131, 'Nuvessa'),
(132, 'NuVet Plus Canine Powder'),
(133, 'NuVet Plus Canine Wafers'),
(134, 'Omega-3'),
(135, 'Omeprazole'),
(136, 'Omnipred'),
(137, 'Ondansetron'),
(138, 'Optimmune Ophthalmic Ointment'),
(139, 'Oracea'),
(140, 'Panacur'),
(141, 'Pawfy Probiotic'),
(221, 'Penicillin'),
(142, 'Pepcid'),
(143, 'Phenobarbital'),
(144, 'Phenylpropanolamine'),
(145, 'Pimobendan'),
(146, 'Plavix'),
(147, 'Pred Forte'),
(148, 'Pred Mild'),
(149, 'Prednisolone'),
(150, 'Prednisone'),
(151, 'Preparation H Ointment'),
(152, 'Prilosec'),
(153, 'Probiotic'),
(154, 'Proin'),
(155, 'Proviable'),
(156, 'Proviable-DC'),
(157, 'Proviable-Forte'),
(158, 'Prozac'),
(159, 'Psyllium Husk Fiber Powder'),
(160, 'Pumpkin Probiotic'),
(161, 'Purina Pro Plan Calming Care Probiotic'),
(162, 'Rayos'),
(163, 'Rimadyl'),
(164, 'Roweepra'),
(165, 'Safe-Guard'),
(166, 'Salix'),
(167, 'Sandimmune'),
(168, 'Sarafem'),
(169, 'Simparica Trio'),
(170, 'Spritam'),
(171, 'Sunscreen'),
(172, 'Synthroid'),
(173, 'Tacrolimus Ophthalmic Solution'),
(174, 'Theo-24'),
(175, 'Theochron'),
(176, 'Theophylline'),
(177, 'ThunderWunders Calming Chews'),
(178, 'Thyro-Tabs Canine'),
(179, 'Thyroxine'),
(180, 'Tirosint'),
(181, 'Tobi Podhaler'),
(182, 'Tobramycin'),
(183, 'Tobrex'),
(184, 'Tramadol'),
(185, 'Trazodone'),
(186, 'Trilostane'),
(187, 'Tylan'),
(188, 'Tylosin'),
(189, 'Ultram'),
(190, 'Unithroid'),
(191, 'URSO 250'),
(192, 'URSO Forte'),
(193, 'Ursodiol'),
(194, 'Vantin'),
(195, 'Vasotec'),
(196, 'Vetmedin'),
(197, 'Vetoryl'),
(198, 'Vetprofen'),
(199, 'Vicodin'),
(200, 'Vicoprofen'),
(201, 'Vitamin'),
(202, 'Vitamin E'),
(203, 'Vivlodex'),
(204, 'Welactin Omega-3 Supplement'),
(205, 'WINPRO Pet Supplement'),
(206, 'Xalatan'),
(207, 'Xanax'),
(208, 'Xolegel'),
(209, 'Zegerid'),
(210, 'Zesty Paws Aller-Immune Bites'),
(211, 'Zesty Paws Multifunctional Bites'),
(212, 'Zesty Paws Probiotic Bites'),
(213, 'Zofran'),
(214, 'Zonegran'),
(215, 'Zonisamide'),
(216, 'Zuplenz'),
(217, 'Zyrtec');

SET FOREIGN_KEY_CHECKS=1;
