DROP DATABASE IF EXISTS boarding;
CREATE DATABASE boarding;
USE boarding;
SET FOREIGN_KEY_CHECKS=0;
SET NAMES utf8;
SET character_set_client=utf8mb4;

CREATE TABLE condos (
  condoID INT(11) NOT NULL,
  columnID INT(11) NOT NULL,
  rowID INT(11) NOT NULL,
  groupID INT(11) NOT NULL,
  status ENUM('Enabled', 'Disabled') NOT NULL DEFAULT 'Enabled',
  PRIMARY KEY (condoID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO condos (condoID, columnID, rowID, groupID, status) VALUES
(1, 1, 1, 1, 'Enabled'),
(2, 2, 1, 1, 'Enabled'),
(3, 2, 1, 2, 'Enabled'),
(4, 2, 2, 2, 'Enabled'),
(5, 2, 3, 2, 'Enabled'),
(6, 2, 4, 2, 'Enabled'),
(7, 2, 5, 2, 'Enabled'),
(8, 1, 2, 1, 'Enabled'),
(9, 2, 2, 1, 'Enabled'),
(10, 1, 1, 2, 'Enabled'),
(11, 1, 2, 2, 'Enabled'),
(12, 1, 3, 2, 'Enabled'),
(13, 1, 4, 2, 'Enabled'),
(14, 1, 5, 2, 'Enabled');

CREATE TABLE cats (
  catID INT(11) NOT NULL AUTO_INCREMENT,
  condoID INT(11) NOT NULL,
  catName VARCHAR(255) NOT NULL,
  foodType ENUM('Own', 'Ours') NOT NULL,
  feedingInstructions TEXT NOT NULL,
  foodAllergies ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  separateToFeed ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  noSlipBowl ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  plasticBowl ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  slowFeeder ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  elevatedFeeder ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  status ENUM('Active', 'Future') NOT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (catID),
  FOREIGN KEY (condoID) REFERENCES condos(condoID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cats_medications (
  catMedID INT(11) NOT NULL AUTO_INCREMENT,
  catID INT(11) NOT NULL,
  medName VARCHAR(255) NOT NULL,
  strength VARCHAR(100) DEFAULT NULL,
  dosage TEXT NOT NULL,
  frequency ENUM('AM', 'PM', '2X', '3X', 'As Needed', 'Other') NOT NULL,
  notes TEXT DEFAULT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (catMedID),
  FOREIGN KEY (catID) REFERENCES cats(catID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cats_reservations (
  catReservationID INT(11) NOT NULL AUTO_INCREMENT,
  condoID INT(11) NOT NULL,
  catName VARCHAR(255) NOT NULL,
  checkIn DATE NOT NULL,
  checkOut DATE NOT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (catReservationID),
  FOREIGN KEY (condoID) REFERENCES condos(condoID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE rooms (
  roomID INT(11) NOT NULL,
  columnID INT(11) NOT NULL,
  rowID INT(11) NOT NULL,
  groupID INT(11) NOT NULL,
  status ENUM('Enabled', 'Disabled') NOT NULL DEFAULT 'Enabled',
  PRIMARY KEY (roomID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO rooms (roomID, columnID, rowID, groupID, status) VALUES
(1, 1, 16, 2, 'Enabled'),
(2, 1, 15, 2, 'Enabled'),
(3, 1, 14, 2, 'Enabled'),
(4, 1, 13, 2, 'Enabled'),
(5, 1, 12, 2, 'Enabled'),
(6, 1, 11, 2, 'Enabled'),
(7, 1, 10, 2, 'Enabled'),
(8, 1, 9, 2, 'Enabled'),
(9, 1, 8, 1, 'Enabled'),
(10, 1, 7, 1, 'Enabled'),
(11, 1, 6, 1, 'Enabled'),
(12, 1, 5, 1, 'Enabled'),
(13, 1, 4, 1, 'Enabled'),
(14, 1, 3, 1, 'Enabled'),
(15, 1, 2, 1, 'Enabled'),
(16, 1, 1, 1, 'Enabled'),
(17, 2, 16, 2, 'Enabled'),
(18, 2, 15, 2, 'Enabled'),
(19, 2, 14, 2, 'Enabled'),
(20, 2, 13, 2, 'Enabled'),
(21, 2, 12, 2, 'Enabled'),
(22, 2, 11, 2, 'Enabled'),
(23, 2, 10, 2, 'Enabled'),
(24, 2, 9, 2, 'Enabled'),
(25, 2, 8, 1, 'Enabled'),
(26, 2, 7, 1, 'Enabled'),
(27, 2, 6, 1, 'Enabled'),
(28, 2, 5, 1, 'Enabled'),
(29, 2, 4, 1, 'Enabled'),
(30, 2, 3, 1, 'Enabled'),
(31, 2, 2, 1, 'Enabled'),
(32, 2, 1, 1, 'Enabled'),
(33, 3, 1, 1, 'Enabled'),
(34, 3, 2, 1, 'Enabled'),
(35, 3, 3, 1, 'Enabled'),
(36, 3, 4, 1, 'Enabled'),
(37, 3, 5, 1, 'Enabled'),
(38, 3, 6, 1, 'Enabled'),
(39, 3, 7, 1, 'Enabled'),
(40, 3, 8, 1, 'Enabled'),
(41, 3, 9, 2, 'Enabled'),
(42, 3, 10, 2, 'Enabled'),
(43, 3, 11, 2, 'Enabled'),
(44, 3, 12, 2, 'Enabled'),
(45, 3, 13, 2, 'Enabled'),
(46, 3, 14, 2, 'Enabled'),
(47, 3, 15, 2, 'Enabled'),
(48, 3, 16, 2, 'Enabled'),
(49, 4, 18, 1, 'Enabled'),
(50, 4, 17, 1, 'Enabled'),
(51, 4, 16, 1, 'Enabled'),
(52, 4, 15, 1, 'Enabled'),
(53, 4, 14, 1, 'Enabled'),
(54, 4, 13, 1, 'Enabled'),
(55, 4, 12, 1, 'Enabled'),
(56, 4, 11, 1, 'Enabled'),
(57, 4, 10, 1, 'Enabled'),
(58, 4, 9, 1, 'Enabled'),
(59, 4, 8, 1, 'Enabled'),
(60, 4, 7, 1, 'Enabled'),
(61, 4, 6, 1, 'Enabled'),
(62, 4, 5, 1, 'Enabled'),
(63, 4, 4, 1, 'Enabled'),
(64, 4, 3, 1, 'Enabled'),
(65, 4, 2, 1, 'Enabled'),
(66, 4, 1, 1, 'Enabled');

CREATE TABLE dogs (
  dogID INT(11) NOT NULL AUTO_INCREMENT,
  roomID INT(11) NOT NULL,
  dogName VARCHAR(255) NOT NULL,
  foodType ENUM('Own', 'Ours') NOT NULL,
  feedingInstructions TEXT NOT NULL,
  foodAllergies ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  separateToFeed ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  noSlipBowl ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  plasticBowl ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  slowFeeder ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  elevatedFeeder ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
  status ENUM('Active', 'Future') NOT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (dogID),
  FOREIGN KEY (roomID) REFERENCES rooms(roomID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dogs_medications (
  dogMedID INT(11) NOT NULL AUTO_INCREMENT,
  dogID INT(11) NOT NULL,
  medName VARCHAR(255) NOT NULL,
  strength VARCHAR(100) DEFAULT NULL,
  dosage TEXT NOT NULL,
  frequency ENUM('AM', 'PM', '2X', '3X', 'As Needed', 'Other') NOT NULL,
  notes TEXT DEFAULT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (dogMedID),
  FOREIGN KEY (dogID) REFERENCES dogs(dogID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dogs_reservations (
  dogReservationID INT(11) NOT NULL AUTO_INCREMENT,
  roomID INT(11) NOT NULL,
  dogName VARCHAR(255) NOT NULL,
  checkIn DATE NOT NULL,
  checkOut DATE NOT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (dogReservationID),
  FOREIGN KEY (roomID) REFERENCES rooms(roomID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE medications (
  medID INT(11) NOT NULL AUTO_INCREMENT,
  medName VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (medID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO medications (medName) VALUES
('Aller-Immune Bites'),
('Allergenic Extract'),
('Alprazolam'),
('Amantadine'),
('Animax'),
('Antacid'),
('Antimicrobial Wipes'),
('Apoquel'),
('Atopica'),
('Benadryl'),
('Benazepril'),
('Calming Chews'),
('Calming Treats'),
('Carprofen'),
('Carprovet'),
('CBD Hemp'),
('Cefpodoxime'),
('Cephalexin'),
('Ceraven Wipes'),
('Cerenia'),
('Chlorhexidine Mousse'),
('Clavacillin'),
('Clomipramine'),
('Composure Pro'),
('Cosequin'),
('Dasuquin'),
('Denamarin'),
('Diethylstilbestrol'),
('Digestion Vitamin'),
('Doggie Dailies Joint Supplement'),
('Doxycycline'),
('Ear Flush'),
('Enalapril'),
('Endosorb'),
('Enrofloxacin'),
('Eye Lube'),
('Eye Wash'),
('Famotidine'),
('Fenbendazole'),
('Fish Oil'),
('Flovent'),
('Fluconazole'),
('Fluoxetine'),
('FortiFlora'),
('Furosemide'),
('Gabapentin'),
('Galliprant'),
('Genome Topical Spay'),
('Glandex'),
('Glyco Flex'),
('Heartgard'),
('Honest Paws Well Pre+ Probiotic'),
('Hydrocodone'),
('Imodium'),
('Incurin'),
('Interceptor Plus'),
('Itch Spray'),
('Joint Supplement'),
('Keppra'),
('Ketoconazole'),
('Lactulose'),
('Latanoprost'),
('Levetiracetam'),
('Levothyroxine'),
('Malmetazone'),
('Melatonin'),
('Meloxicam'),
('Metamucil'),
('Metronidazole'),
('Movoflex'),
('Mozotic'),
('Multi-Vitamin'),
('Myos Powder'),
('Neo-Poly-Dex'),
('Neo-Predef'),
('Nexgard'),
('Novox'),
('Nuvet'),
('Omega-3'),
('Omeprazole'),
('Ondansetron ODT'),
('Optimmune'),
('Pawfy'),
('Pepcid'),
('Phenobarbital'),
('Pimobendan'),
('Prednisolone'),
('Prednisone'),
('Preparation H Cream'),
('Prilosec'),
('Probiotic'),
('Proin'),
('Proviable'),
('Proviable-Forte'),
('Prozac'),
('Psyllium Powder'),
('Pumpkin Probiotic'),
('Purina Calming Care'),
('Rimadyl'),
('Simparica Trio'),
('Sunscreen'),
('Tacrolimus Eye Drops'),
('Theophylline'),
('Thunder Wunder'),
('Thyro-Tabs Canine'),
('Thyroxin'),
('Thyroxine'),
('Tobramycin'),
('Tramadol'),
('Trazodone'),
('Tylosin'),
('Ursodiol'),
('Vetmedin'),
('Vetoryl'),
('Vetprofen'),
('Vitamin'),
('Vitamin E'),
('Welactin'),
('WINPRO Pet Supplement'),
('Xanax'),
('Zesty Paws Multifunctional Bites'),
('Zofran'),
('Zonisamide'),
('Zyrtec');

SET FOREIGN_KEY_CHECKS=1;
