DROP DATABASE IF EXISTS kennel;
CREATE DATABASE kennel;
USE kennel;
SET FOREIGN_KEY_CHECKS=0;
SET NAMES utf8;
SET character_set_client=utf8mb4;

CREATE TABLE rooms (
  roomID INT(11) NOT NULL,
  mapColumn INT(11) NOT NULL,
  mapRow INT(11) NOT NULL,
  PRIMARY KEY (roomID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dogs (
  dogID INT(11) NOT NULL AUTO_INCREMENT,
  roomID INT(11) NOT NULL,
  dogName VARCHAR(255) NOT NULL,
  foodType ENUM('Own', 'Ours') NOT NULL,
  feedingInstructions TEXT NOT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (dogID),
  FOREIGN KEY (roomID) REFERENCES rooms(roomID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dogs_medications (
  dogMedID INT(11) NOT NULL AUTO_INCREMENT,
  dogID INT(11) NOT NULL,
  medName VARCHAR(255) NOT NULL,
  strength VARCHAR(100) NOT NULL,
  dosage TEXT NOT NULL,
  frequency ENUM('AM', 'PM', '2X', '3X', 'As Needed') NOT NULL,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (dogMedID),
  FOREIGN KEY (dogID) REFERENCES dogs(dogID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE medications (
  medID INT(11) NOT NULL AUTO_INCREMENT,
  medName VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (medID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
